@extends('layouts.app')

@section('content')
<div class="py-12">
    <div class="max-w-4xl mx-auto sm:px-6 lg:px-8">
        <!-- Header -->
        <div class="mb-8 flex justify-between items-start">
            <div>
                <h1 class="text-3xl font-bold text-gray-900">{{ $kraExport->getTypeLabel() }}</h1>
                <p class="text-gray-600 mt-2">Period: {{ $kraExport->getPeriodLabel() }}</p>
            </div>
            <a href="{{ route('hr.kra-exports.index') }}" class="text-gray-600 hover:text-gray-900">Back</a>
        </div>

        <!-- Alerts -->
        @if (session('success'))
            <div class="bg-green-50 border border-green-200 rounded-lg p-4 mb-6 text-green-800">
                {{ session('success') }}
            </div>
        @endif

        @if ($errors->any())
            <div class="bg-red-50 border border-red-200 rounded-lg p-4 mb-6">
                <div class="text-red-800">
                    @foreach ($errors->all() as $error)
                        <p>{{ $error }}</p>
                    @endforeach
                </div>
            </div>
        @endif

        <!-- Details Card -->
        <div class="bg-white rounded-lg shadow overflow-hidden mb-8">
            <div class="px-6 py-4 bg-gray-50 border-b border-gray-200">
                <h2 class="text-lg font-semibold text-gray-900">Export Details</h2>
            </div>
            <div class="px-6 py-6">
                <div class="grid grid-cols-2 gap-6">
                    <div>
                        <h3 class="text-sm font-medium text-gray-600 mb-1">Export Type</h3>
                        <p class="text-lg text-gray-900">{{ $kraExport->getTypeLabel() }}</p>
                    </div>
                    <div>
                        <h3 class="text-sm font-medium text-gray-600 mb-1">Status</h3>
                        <span class="inline-block px-3 py-1 text-sm font-medium rounded-full
                            {{ $kraExport->status == 'generated' ? 'bg-blue-100 text-blue-800' : '' }}
                            {{ $kraExport->status == 'submitted' ? 'bg-yellow-100 text-yellow-800' : '' }}
                            {{ $kraExport->status == 'approved' ? 'bg-green-100 text-green-800' : '' }}
                            {{ $kraExport->status == 'rejected' ? 'bg-red-100 text-red-800' : '' }}">
                            {{ $kraExport->getStatusLabel() }}
                        </span>
                    </div>
                    <div>
                        <h3 class="text-sm font-medium text-gray-600 mb-1">Period</h3>
                        <p class="text-lg text-gray-900">{{ $kraExport->getPeriodLabel() }}</p>
                    </div>
                    <div>
                        <h3 class="text-sm font-medium text-gray-600 mb-1">Record Count</h3>
                        <p class="text-lg text-gray-900">{{ $kraExport->record_count }} records</p>
                    </div>
                    <div>
                        <h3 class="text-sm font-medium text-gray-600 mb-1">Total Amount</h3>
                        <p class="text-lg text-gray-900">KES {{ number_format($kraExport->total_amount ?? 0, 2) }}</p>
                    </div>
                    <div>
                        <h3 class="text-sm font-medium text-gray-600 mb-1">Generated By</h3>
                        <p class="text-lg text-gray-900">{{ $kraExport->user->name ?? 'System' }}</p>
                    </div>
                    <div>
                        <h3 class="text-sm font-medium text-gray-600 mb-1">Generated At</h3>
                        <p class="text-lg text-gray-900">{{ $kraExport->exported_at?->format('Y-m-d H:i:s') ?? '-' }}</p>
                    </div>
                    <div>
                        <h3 class="text-sm font-medium text-gray-600 mb-1">Submitted At</h3>
                        <p class="text-lg text-gray-900">{{ $kraExport->submitted_at?->format('Y-m-d H:i:s') ?? 'Not submitted' }}</p>
                    </div>
                </div>

                @if ($kraExport->notes)
                    <div class="mt-6 pt-6 border-t border-gray-200">
                        <h3 class="text-sm font-medium text-gray-600 mb-2">Notes</h3>
                        <p class="text-gray-900">{{ $kraExport->notes }}</p>
                    </div>
                @endif
            </div>
        </div>

        <!-- Actions -->
        <div class="bg-white rounded-lg shadow p-6 mb-8">
            <h2 class="text-lg font-semibold text-gray-900 mb-4">Actions</h2>
            <div class="space-y-3">
                <a href="{{ route('hr.kra-exports.download', $kraExport) }}" class="block bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-lg text-center">
                    Download CSV File
                </a>
                @if ($kraExport->status == 'generated')
                    <form action="{{ route('hr.kra-exports.mark-submitted', $kraExport) }}" method="POST">
                        @csrf
                        <div class="mb-3">
                            <label class="block text-sm font-medium text-gray-700 mb-2">Submission Notes (Optional)</label>
                            <textarea name="notes" rows="3" class="w-full px-3 py-2 border border-gray-300 rounded-lg" placeholder="Add any notes about this submission..."></textarea>
                        </div>
                        <button type="submit" class="w-full bg-yellow-600 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded-lg">
                            Mark as Submitted to KRA
                        </button>
                    </form>
                @endif
                @if ($kraExport->status == 'generated')
                    <form action="{{ route('hr.kra-exports.destroy', $kraExport) }}" method="POST" onsubmit="return confirm('Delete this export?');">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="w-full bg-red-600 hover:bg-red-700 text-white font-bold py-2 px-4 rounded-lg">
                            Delete Export
                        </button>
                    </form>
                @endif
            </div>
        </div>

        <!-- File Information -->
        <div class="bg-white rounded-lg shadow p-6">
            <h2 class="text-lg font-semibold text-gray-900 mb-4">File Information</h2>
            <div class="space-y-2">
                <div>
                    <span class="text-sm font-medium text-gray-600">File Name:</span>
                    <p class="text-gray-900 font-mono">{{ $kraExport->file_name }}</p>
                </div>
                <div>
                    <span class="text-sm font-medium text-gray-600">File Path:</span>
                    <p class="text-gray-600 font-mono text-sm">{{ $kraExport->file_path }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
